### ISSUE TITLE
not allowed ModeratorCmds[] are shown 

### ISSUE THREAD

**Issue by Warsheep-GER** [ole1986/a3-adminhelper#13]
as moderator any command is shown in the list , but not runnable.

**Comment by ole1986** [comment]
Is this still an issue in the latest version?

**Comment by ole1986** [comment]
Still an issue in latest commit?

**Comment by Warsheep-GER** [comment]
need to test it

**Comment by ole1986** [comment]
will close it for now please reopen if needed
