### ISSUE TITLE
standard commands moving to @mission/atk folder?

### ISSUE THREAD

**Issue by Warsheep-GER** [ole1986/a3-adminhelper#21]
for a better overview/changes and as a good template
i would say to move the standard commands to the atk folder in the 
@mission/atk/standard
for the mods i would say to add this folder
@mission/atk/mod
and the messages can stay in @mission/atk or moved to a atk system folder @mission/atk/system
i know thats this is the way to bring up the missionfile size. but it will be easyer to edit/template all stuff
. we dont need to move the login command who needs any ppl
 like getvehicle/items ec. i think it would be nice .

**Comment by ole1986** [comment]
Mhm good idea but I would do only two folders.
Like "system" and "mod".

Login script you meant the "init.sqf" I guess

**Comment by Warsheep-GER** [comment]
login script(command i mean the login cmd

case 'login':
        {
            // send login ok with moderator cmdlets
            ['loginok', _moderatorCmds] remoteExecCall ['AdminToolkit_network_receiveResponse', owner _player];
        };
this dosnt need to be in the mission file , also like kickplayers / banplayers who dosnt need to be changed .
but getvehicle giveammo ec, i would move to standard/system folder in the @mission file. so any admin can chosen whats menu will be included (i know its implementet with 
**ExcludeMenu[]**) but with this way  anyone have a template for changes ec. 
the standard commands are divided up on admintoolkit_server and @AdminToolkit and need a other main code like the ext.
 so as an example  ther is difficult to found out how make an Extensions playerlist ( u know the most serveradmins cant read codes) i know its easy 1 line , 

 [player, 'getplayers'] remoteExecCall ['AdminToolkit_network_receiveRequest', `2];`

for better explain my shit english we need to talk i think :D

**Comment by ole1986** [comment]
this is confusing...

if you want player being able to get money, they should install the admin tool and become moderator...

"normal" player will only have the "message" feature in the mission file to actually "display" the message... most other things can be achieved from server directly i think.

**Comment by ole1986** [comment]
partly solved -rest can be again issued if necessary
