### ISSUE TITLE
repeat button/f5 not work correctly

### ISSUE THREAD

**Issue by Warsheep-GER** [ole1986/a3-adminhelper#22]
example case1:
i spawn a vehicle for me (getvehicle/ exile_getvehicle)
repaired the vehicle (exile_repvehicle)
need to repair it again hit f5(click the repeat button)  but its spawn a new vehicle .

think its case of ext commands variable (
exile_getvehicle is working bec 
`[AdminToolkit_Action] call AdminToolkit_doAction;`
exile_repvehicle isnt working bec 
`[player, 'exile_repvehicle', cursorObject] remoteExecCall ['AdminToolkit_network_receiveRequest', 2];`

with the standard commands i dosnt found a case, ( getitems ,message ec) 

and the hotkey f5 dosnt work anytime

**Comment by ole1986** [comment]
Using the remoteexec isn't a good solution at all.
For example Battleye need additional restrictions for any remoteexec being called on different places.

So my recommendation is to replace it with the usual AdminToolkit_doAction call...
This would solve the BE restriction as well as the repeat function..

Are you motivated to fix this issue the way I suggested?

**Comment by Warsheep-GER** [comment]
sure will overwork this with AdminToolkit_doAction

**Comment by ole1986** [comment]
how is it going with this issue?
