### ISSUE TITLE
new Pictures bring up some issue

### ISSUE THREAD

**Issue by Warsheep-GER** [ole1986/a3-adminhelper#23]
on the Others list its give some warning messages: Picture picturestaticobject not found
its spam 500 lines (-+) in the client log 

on the other lists we get some stuff without an image (using an ? default image when no img is givnt)

and on playerlist we dont need invisible pics. ther we can add the mainweapon or so as an info to the player

**Comment by ole1986** [comment]
show weapons from every player is not avaialble yet, as server only sends the player names and no player objects

**Comment by Warsheep-GER** [comment]
with 
`parseText format ["Image:<br/><img image='%1' size='7'/>", getText (configFile >> 'CfgWeapons' >> primaryWeapon player >> 'picture')];`
its should be work to get the weapons from the players,

**Comment by ole1986** [comment]
player would only be for the current player not all players... receiveing a player list from local player is usally restricted through BE filters as it does not make sense to allow clients receiving player objects of other players..

**Comment by hobart666** [comment]
Have it call the db...

**Comment by ole1986** [comment]
Implemented to primary weapon into version 2.03
