### ISSUE TITLE
Add Weapons Vehicles from CUP 

### ISSUE THREAD

**Issue by HellBz** [ole1986/a3-adminhelper#29]
i Setup my  Exile Server with CUP-Units, CUP-Vehicles and CUP-Waepons

i Search many Hours Classnames for Spawn Vehicles in Adminmenu or Additional Wespons and More from CUP.

I Found: 
http://wiki.cup-arma3.org/index.php?title=Arma_3_CfgVehicles_WEST
http://wiki.cup-arma3.org/index.php?title=Arma_3_CfgVehicles_EAST
http://wiki.cup-arma3.org/index.php?title=Arma_3_CfgVehicles_GUER
http://wiki.cup-arma3.org/index.php?title=Arma_3_CfgVehicles_CIV

But nothing is Work, can Anyone Help me ??

i tried:
_result = "(getText(_x >> 'VehicleClass') in ['CUP_B_Dingo_CZ_Des', 'CUP_B_GER', 'CUP_WheeledVehicles_Dingo', 'CUP_Vehicles_cfgGroups', 'CUP_Vehicles', 'CUP_TrackedVehicles_Bradley', 'CUP_WheeledVehicles', ....................

Nothing Work, PLS Help Me

**Comment by ole1986** [comment]
Hi, 
Nit sure about the vehicleClass. Maybe you try something different... E.g.

`_result = "(
    ((configName _x) isKindOf 'Helicopter') &&
    {getNumber (_x >> 'scope') >= 2}
    )" configClasses (configFile >> "CfgVehicles");`

scope is used to show only public classes

**Comment by HellBz** [comment]
GOT IT 

`_result = "(getText(_x >> 'VehicleClass') in ['ExileCars', 'ExileBikes', 'ExileChoppers','ExileBoats','ExilePlanes']) and (getNumber (_x >> 'scope') == 2)" configClasses (configFile >> "CfgVehicles");
`

to 

`_result = "(getText(_x >> 'VehicleClass') in ['Submarine', 'Ship', 'Armored', 'Air', 'Car', 'Support', 'Autonomous', 'ExileCars', 'ExileBikes', 'ExileChoppers','ExileBoats','ExilePlanes']) and (getNumber (_x >> 'scope') == 2)" configClasses (configFile >> "CfgVehicles");
`
