### ISSUE TITLE
Server Key and client key not working

### ISSUE THREAD

**Issue by CrazymanNL** [ole1986/a3-adminhelper#32]
Hey I got the admin tool working only when i put verifySignatures = 0 how can i change it so it work for verifySignatures = 2 aswell

**Comment by ole1986** [comment]
Possible *.bisign files missing?!

**Comment by CrazymanNL** [comment]
at least I don't think so well in the server mod it's not there but in the client one yes there is the pbo and the bisign

[http://i.imgur.com/qo3MdEv.png]Screenshots1 
[http://i.imgur.com/vDOf232.png]Screenshots2

**Comment by CrazymanNL** [comment]
It's ok I found it out you have to drag the key in the keys folder LOL
