### ISSUE TITLE
GodMode for RyanZombies mod

### ISSUE THREAD

**Issue by ole1986** [ole1986/a3-adminhelper#34]
The god mode does not work with zombie mods, like RyanZombies.
To achieve this, the must be a proper check on how the zombie mod causes the player to become damage

Later implement an update god mode to get more reliable

**Comment by Warsheep-GER** [comment]
If i remember me right, Ryan zombies used a simple set damage code snipped for  the attacking. So the godmode dosnt work right bec its not real damage from the zombis.

**Comment by ole1986** [comment]
@Warsheep-GER thank you - do you have any idea how to resolve it? - So the god mode can also work work this?

**Comment by Warsheep-GER** [comment]
Sry, i dont know a clean way for this. Only have temp fix but its a Performance killer.  Use a loop who give u health. Or a better way,   make a loop with a zombiecleanup 10m near the player

**Comment by ole1986** [comment]
thank you
