### ISSUE TITLE
Replace lower buttons with DropDown - review concept?

### ISSUE THREAD

**Issue by ole1986** [ole1986/a3-adminhelper#4]
The lower buttons are possible to overwrite using the CfgAdminToolkitCustomMod class from the mission file.

This allows you to set custom action and text to all the IDC available in the tool

Example: 

```
/*
 * ----------------------
 * | 1701 | 1702 | 1703 |
 * ----------------------
 * | 1704 | 1705 | 1706 |
 * ----------------------
 * ----------  ----------
 * |  1707  |  |  1708  |
 * ----------  ----------
 */
// Overwrite the button with IDC 1707 with new text "Exile Spawn" followed by the action to be called
[1707, "Exile Spawn", "['exile_getvehicle'] call AdminToolkit_buttonAction;"] call AdminToolkit_uiButton;`
// [...]
```

Should we replace the Buttons with a drop down menu allowing developers to implement almost unlimited no of actions?

```
 -------------------------
| (Select Action)      \/ |
--------------------------
 | Action 1             |
 | Action 2             |
 | (...)                |
 ------------------------
```

**Comment by Warsheep-GER** [comment]
i would say the buttons are better as a scrollmenu. but add a 1709 button 

```
class RscAdminToolkitAction7: RscButton
{
    idc = 1707;
    action = "";
    x = 0.775034 * safezoneW + safezoneX;
    y = 0.87294 * safezoneH + safezoneY;
    w = 0.0625 * safezoneW;
    h = 0.04 * safezoneH;
};
class RscAdminToolkitAction8: RscButton
{
    idc = 1708;
    action = "";
    x = 0.850006 * safezoneW + safezoneX;
    y = 0.87294 * safezoneH + safezoneY;
    w = 0.0625 * safezoneW;
    h = 0.04 * safezoneH;
};
class RscAdminToolkitAction8: RscButton
{
    idc = 1709;
    action = "";
    x = 0.924978 * safezoneW + safezoneX;
    y = 0.87294 * safezoneH + safezoneY;
    w = 0.0625 * safezoneW;
    h = 0.04 * safezoneH;
```

and add some site/tab button for switch the button action

/*
- ----------------------
-  |#S1# | S2| S3 |S4 |S5|
- ----------------------
- | 1701 | 1702 | 1703 |
- ----------------------
- | 1704 | 1705 | 1706 |
- ----------------------
- | 1707 | 1708 | 1709 |
- ----------------------
  _/
  /_
- ----------------------
- |S1 | # S2#| S3 |S4 |S5|
- ----------------------
- | 1711 | 1712 | 1713 |
- ----------------------
- | 1714 | 1715 | 1716 |
- ----------------------
- | 1717 | 1718 | 1719 |
- ----------------------
  */

the selm for the top menu, thats would be enugh and the overview isnt destroyed like in a scroll menu

**Comment by Warsheep-GER** [comment]
*the top menu dosnt need that side/tab feature, just add the 1701-09 buttons on the first menusection when u push f2. then u have 8/9(1709) buttons for adminowncomands like godemode / money respect ec. then we have space in the playerscreen for 3/4(1709)  new playercomands.

**Comment by ole1986** [comment]
I actually do not want to have a focus on these "adminowncommands" as individual cmdlets
I would prefer to categories the commands to either  player, vehicles mods, buildings, etc...understand what I mean?

What about this solution?

**First Concept**

```
+-------------------------------------+
| +--------+  +---------+ +---------+ |
| | Player |  | Vehicles| | Other   | |
| +--------+  +---------+ +---------+ |
| +--------+  +---------+ +---------+ |
| |Mod 1   |  | Mod 2   | | Mod 3   | |
| +--------+  +---------+ +---------+ |
| +---------------------+ +---------+ |
| |(Text Search)        | | Search  | |
| +---------------------+ +---------+ |
| +---------------------------------+ |
| | Player #1                       | |
| |                                 | |
| | Player #2                       | |
| |                                 | |
| | Player #3                       | |
| |                                 | |
| | (...)                           | |
| |                                 | |
| |                                 | |
| +---------------------------------+ |
|                                     |
|  ########### LABEL #1 ############<------+ Used to display
|                                     |      selected player
|                                     |      or any other info
| +-----------------------+ +-------+ |
| |(Select action)      \/| |Execute| |
| +-----------------------+ +-------+ |
+-------------------------------------+
```

Source: http://asciiflow.com/

**Comment by ole1986** [comment]
**Second Concept**

```
   +-------------------------------------+
   | +---------------------+ +---------+ |
   | |(Select Menu)     \/ | | Select  | |
   | +---------------------+ +---------+ |
   |                                     |
   |  ### LABEL <SELECTED MENU> ### <-------+ Used to display the
   |                                     |    current selected main
   | +---------------------+ +---------+ |    menu
   | |(Text Search)        | | Search  | <---+
   | +---------------------+ +---------+ |   |
   | +---------------------------------+ |   +
   | | Player #1                       | |   Search applies to any main
   | |                                 | |   menu selected on top.
   | | Player #2                       | |   So either it can be used to
   | |                                 | |   search in players or vehicles
   | | Player #3                       | |   etc...
   | |                                 | |
   | | (...)                           | |
   | |                                 | |
   | |                                 | |
   | +---------------------------------+ |
   |                                     |
   |  ########### LABEL #1 ############ <---+ Used to display
   |                                     |    selected player
   |                                     |    or any other info
   | +-----------------------+ +-------+ |
+--> |(Select action)      \/| |Execute| |
|  | +-----------------------+ +-------+ |
|  +-------------------------------------+
|
+
Autoload the action menu dependent on which
main menu has been selected

```

Source: http://asciiflow.com/

**Comment by Warsheep-GER** [comment]
ya np , i stoped it alreddy and wait for the new gui ;)

i think case 2 will be good, but without  
   |  ### LABEL <.SELECTED MENU> ### <-------+

 | +----------------------------------+ |
 | |(Select Menu) [Show Selected] \/ | |
 | +----------------------------------+ |

**Comment by ole1986** [comment]
Labels are primary used to inform Admins about actions

How about concept 3:

```
+-------------------------------------+
|                                     |
| +---------------------+ +---------+ |
| | (Choose menu)    \/ | | SELECT  | |
| +---------------------+ +---------+ |
|                                     |
| ### LABEL 1 ###                     |
|                                     |
| +---------------------+ +---------+ |
| | (Filter)         \/ | | SEARCH  | |
| +---------------------+ +---------+ |
|                                     |
| +---------------------------------+ |
| |                                 | |
| | Player #1                       | |
| | Player #2                       | |
| | Player #3                       | |
| |                                 | |
| |                                 | |
| |                                 | |
| |                                 | |
| |                                 | |
| |                                 | |
| +---------------------------------+ |
|                                     |
| ### LABEL 2 ###                     |
|                                     |
| +---------------------+ +---------+ |
| | (select action)  \/ | | Execute | |
| +---------------------+ +---------+ |
|                                     |
| +---------------------+ +---------+ |
| | (custom code)       | | Execute | |
| +---------------------+ +---------+ |
|                                     |
+-------------------------------------+
```

**Comment by Warsheep-GER** [comment]
| +---------------------+ +---------+ |
| | (select action)  \/      | | Execute   | |
| +---------------------+ +---------+ |
| ### LABEL 2 ###                            |

would be look better

(custom code)  what u mean with this? like this ?
 money  
4209 

or compleet custom , thats u can enterd a code to exect?

**Comment by ole1986** [comment]
Mmm.. lets rename `custom code` to `custom parameter`

This would allow an admin to customize the parameter(ds) for an action specified in `(select action)`

For example:
1. admin has selected `Players` from the `Main Menu`
2. Then selects `Player 2` from the player list
3. `### LABEL 2 ###` prints out "Player 'Player 2' has selected"
4. admin selects the action `Say To` and enters custom text "No admin abuse" into `custom parameter` field
5. admin clicks on `Execute` and a message will be send to "Player 2"

**Comment by ole1986** [comment]
Another Example:
1. admin aims to a vehicle (he/she want to destroy)
2. Then press F2 and selects `Vehicles` from `Main Menu`
3. Before selecting `Destroy Vehicle` from the `(action menu)`, he/she enters a number of seconds into the `custom parameter` box
4. Then selects the action "Destroy Vehicle" and press `Execute`
5. Vehicle will be destroyed in `number of seconds` he/she enters in the `custom parameter`

**Comment by Warsheep-GER** [comment]
Ah ok Ya this a Gold Idee. But then remove 1 execute buttom.

**Comment by ole1986** [comment]
Of course! 😁

**Comment by ole1986** [comment]
Final version:

```
                      +-------------------------------------+
                      |                                     |
                      | +---------------------+ +---------+ |
                      | | (Choose menu)    \/ | | SELECT  | <------+
                      | +---------------------+ +---------+ |      +
                      |                                     | Replaced registers with
         +------------> ### LABEL 1 ###                     | DropDown Main Menu
         +            |                                     |
Login and server      | +---------------------+ +---------+ |
notifications, etc... | | (Filter)         \/ | | SEARCH  | <------+
                      | +---------------------+ +---------+ |      +
                      |                                     | Filter option for
                      | +---------------------------------+ | the below list
                      | |                                 | |
                      | | Player #1                       | |
                      | | Player #2                       | <-------+
                      | | Player #3                       | |       +
                      | |                                 | | Display either
                      | |                                 | | Player, Vehicles,
                      | |                                 | | Buildings, Items,
                      | |                                 | | etc...
       Action related | |                                 | |
       notifications  | |                                 | |
           +          | +---------------------------------+ |
           |          |                                     |
           +----------> ### LABEL 2 ###                     |
                      |                                     |
                      | +---------------------+ +---------+ | RUN THE ACTION
            +---------> | (select action)  \/ | |         | |         +
            +         | +---------------------+ |         | |         |
      Choose actions  |                         | Execute | <---------+
      from DropDown   | +---------------------+ |         | |
      list once main  | | (custom code)       | |         | |
      menu is selecte | ++--------------------+ +---------+ |
                      |  ^                                  |
                      +-------------------------------------+
                         |
                         |      add some optional parameters
                         +----+ to the selected action
```

**Comment by Warsheep-GER** [comment]
Ya just the format u need change a Bit ;P

**Comment by Warsheep-GER** [comment]
ps. if u finished with the new hud and (possible) new command code. shared it with me personaly bevore shared it public , i will overwork/add all the commands i have done with my update 2(+) what we changed to the background because the new overlay is importanter . 
so u have just one big update for ur guys ;)

**Comment by ole1986** [comment]
@Warsheep-GER  sounds good to me!
I wanted to do a branch anyway for this...

I will also put you into it as contributer so you can add you changes to this branch or create additional branches directly into the original.

No worries you cannot overwrite the master branches as this is protected by me

Read more about git branch here: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Comment by Warsheep-GER** [comment]
Ya ok. I will look this when im on my pc.  Just need too look how its works with github Desktop.  Then its Should be allright.

**Comment by Warsheep-GER** [comment]
first reply from my admins, the new design(scollmenu) is shit. its take to long to search the menu/command and the overview is to confused

**Comment by ole1986** [comment]
@Warsheep-GER it should actually not have shown to others yet but anyway I was already thinking to imrove this a bit by adding a "remember" function - So the ATK will reopen the last main menu and select the last action the admin has done...

**Comment by Warsheep-GER** [comment]
my admins are ok and they test for me since years a lot of stuff ;)

buti overthink what they talk to me with the dropdown menu.
they are right, its not confortable with it. the rememberfunktion u done with the last sync is nice, but not the right way for the handling.
what u think about this idea
removed the dropdown menu and add a scrollmenu with 5-10(or more) shown action^s/menu^s
 or to redisigne the compleet overview.
u holdet on the "A4" format. but we can change this like:

![image](https://cloud.githubusercontent.com/assets/8508286/17254746/602a22f0-55b6-11e6-91f3-f2d0a2eb976b.png)

with the scollmenu u dont have the overlapped dropdown , u see more infos and can handle faster . with ur rememberfunktion it will be the non+ultra i think .

**Comment by ole1986** [comment]
@Warsheep-GER I was already thinking to replace the DRopDown on top with a listbox..
your concept looks also interessting...
What if do a poll? if they like your idea?

**Comment by Warsheep-GER** [comment]
i would say we need to talk. i have some other ideas about the design, Then we can focus us on 2-3 concepte and do a poll

**Comment by ole1986** [comment]
check out the last commit it contains 4 quick buttons configurable through missionFile config

**Comment by ole1986** [comment]
concept is kept as before - but open minded for future amendmends
