### ISSUE TITLE
ExileMod is not loading with ATK

### ISSUE THREAD

**Issue by ChaosToaster** [ole1986/a3-adminhelper#43]
Hey Guys,

i have a Problem i install the Complete ATK with Furniture and Vanilla and the Problem ist, if it try to make something InGame in the ExileMod Menu i got this Error:

` 3:25:33 Warning Message: Script x\admintoolkit_servercfg\extension\ExileMod.sqf not found
 3:25:33 Warning Message: Script x\admintoolkit_servercfg\extension\VanillaAI.sqf not found
 3:25:33 Warning Message: Script x\admintoolkit_servercfg\extension\Furniture.sqf not found
`

Furniture works perfectly and Vanilla i cant use cause i got the Message in Chat: "Is not inplement yet. Coming soon...". So pls can you help me that i can use the ExileMod Menu?

Thx and have a nice Day :)

**Comment by ole1986** [comment]
can you please make sure the @AdminToolkit folder is only Installed on the client and only the @AdminToolkitServer folder is copied to the server!

Do not copy both folders onto the server

**Comment by ChaosToaster** [comment]
The Serverfolder is on Server and the other Folder on my PC but the ExileModMenu dont works. I mean, i see the Menu ingame in the ATK and i can click on that but if i try to give myself money or something i got the Error i write above this Post.

I post for you my edit files, maybe its my fault cause iam to stupid for that. Idk...

**MissionFile: Exile.Malden config:**

`class CfgAdminToolkitCustomMod {
	/* Exclude some main menu items
	 * To only show the menus loaded from an extension, use:
	 * 
	 * ExcludeMenu[] = {"Players", "Vehicles", "Weapons" , "Other"};
	 */
	ExcludeMenu[] = {};
	
	Extensions[] = {
		{"Exile Mod","ExileMod"},
		{"Vanilla AI","VanillaAI"},
		{"Stoll Furniture","Furniture"}
	};
	
	/* 4 Quick buttons allowing to add any action you want - See example below*/
	QuickButtons[] = {
		/* send a chat message to selected player containing 'Test 123' */
		{"Chat", "['message', [AdminToolkit_Player, 'Test 123']] call AdminToolkit_doAction"},
		/* send a message to everyone using the parameters text field */
		{"Msg To All", "['messageall', AdminToolkit_Params] call AdminToolkit_doAction"},
		/* Quickly get a Helicopter */
		{"Heli", "['getvehicle', 'B_Heli_Light_01_armed_F'] call AdminToolkit_doAction"},
	};
};`


**MissionFile: Exile.Malden description.ext:**

`#include "config.cpp"

Extensions[] = {
		/**
		 * Usage: "<Your Mod Title>", "<YourModFileWithoutExt>.sqf"
		 */
		{"Exile Mod","ExileMod"},
		{"Vanilla AI","VanillaAI"},
		{"Stoll Furniture","Furniture"}
	};`


In the Missionfile i have the ATK Folder -> extension -> and all 3 SQF (ExileMod, Furniture, VanillaAI)

And the ATK_servercfg is correct with PW and my Steam-ArmaUID.
I dont know what i make wrong. I make both Tutorials, that from YouTube and here on Github and the piont is, if i make that EXACTLY how in the tutorial, i dont see the Furniture InGame in the ATK Menu. Maybe the Tutorial is outdated cause its 2-3 Years old. I hope you can help me.

BTW, sry for my bad English, iam German but i try my Best :)

**Comment by ChaosToaster** [comment]
BTW i start A3 only with Exile and ATK mod. Nothing other Mod is loading in there.

**Comment by ole1986** [comment]
Have you repacked the admintoolkit_servercfg.
If yes, which packer you have choosen?

**Comment by ole1986** [comment]
A possible reason, why the files you mentioned above are not being found is that the $pboprefix$ file is not properly recognized by the packing tool.

**Usually I use the AddonBuilder for server / client pbos**
**And FileBank to pack the mission files**

The AddonBuild accepts the $PBOPREFIX$ file while FileBank ignores it. That is why its important to pack ther server files with AddonBuilder

**Comment by ChaosToaster** [comment]
I use PBO Manager, that i used for years without problems.
Maybe u can help me with Teamviewer cause thats way fastern than here in Forum cause u can see/use my Computer.

**Comment by ChaosToaster** [comment]
I used Addon Builder for the admintoolkitcfg now but on my missionfile Exile.Malden i got this error

http://prntscr.com/jbk9p5

And i have a Problem with Addon Builder cause its packed not complete. The extension Folder is not in the PBO, idk why...

**Comment by ole1986** [comment]
use filebank for the mission file to pack it

**Comment by ChaosToaster** [comment]
Same Problem. I delete ATK cause i have not the motivation to fix every Day something on this Mod. I got some errors in Console and more....
I need german Support for that and somebody user what helps me.

**Comment by ole1986** [comment]
I can imaging being the only one having issues with ATK can be very frustrating.
You can send me a pm on exilemod.com and we can arrange a remote support (even in german).

My username on exilemod.com: Ole

Thank you
