### ISSUE TITLE
description.ext could not be found

### ISSUE THREAD

**Issue by Toadstooliv** [ole1986/a3-adminhelper#46]
When I try to patch the PBO for antistasi it says description.ext could not be found but I can clearly see it with PBO manager

**Comment by ole1986** [comment]
How do you patch it? is the $PBOPREFIX$ file probably set?

**Comment by Toadstooliv** [comment]
I'm using the powershell terminal in VSCode like in the instructions, Looking in $PBOPREFIX$ it has x\admintoolkit_servercfg

**Comment by ole1986** [comment]
The admintoolkit_servercfg actually does not contain any description.ext. Same to the admintoolkit_server .pbo (server-side) and the admintoolkit.pbo (client-side)

The `description.ext` is primary stored in mission files. 
Further details about that file can be found here: https://community.bistudio.com/wiki/Description.ext

**Comment by Toadstooliv** [comment]
I figured this out, it had to do with the fact that I keep my steam games in a separate library than the default one so I had to edit the steam path in setup.ps1
