### ISSUE TITLE
Q: Do you have a comprehensive configuration

### ISSUE THREAD

**Issue by mwpowellhtx** [ole1986/a3-adminhelper#50]
I see the animated GIF running, but I am looking for an enumeration of the configuration if possible. Do you have some documentation concerning that? Would be very helpful. Also, getting started, I assume this runs seamlessly with the `mikero` tools? Thanks!

**Comment by mwpowellhtx** [comment]
Apologies if these seem like obvious questions:

* `title` - in lieu of what?
* `name` - example please, such as `name.pbo`?
* `steamPath` - auto detecting what? Arma/Steam install path?
* `buildPath` - seems fairly straightforward; i.e. `bin`? examples would be helpful, i.e. `bin\name.pbo`?
* `privateKey` - examples please. relative to the project workspace?
* `serverDir` - not sure I understand what client/server is for. in terms of engaging with a client and/or server instance of A3?
* `serverUse32bit` - seems fairly straightforward; I assume that 64-bit is default today?
* `serverMods` - not sure I understand this one, does this mean `dependencies`?
* `clientDirs` - questions along similar lines as `serverDir`.
* `clientMods` - ditto `clientDirs` re: `clientDirs`.
* `version` - not implemented how? would be helpful if this was somehow relayed.
* `ftpConnection` - not sure I understand the significance of having an SFTP capability? kind of a modding newbie myself, so maybe for mod deployment?
* `ftpConnectionFile` - ditto `ftpConnection`. not new to FTP, but, yes, as it relates to supporting a A3 modding workflow.
* `postProcess` - in what context? language? etc?

**Comment by ole1986** [comment]
Your question related to
https://github.com/ole1986/vscode-arma-dev/blob/master/schemas/arma-dev.schema.json

**Comment by mwpowellhtx** [comment]
Great thank you. I'll follow up if I have any further questions.
