### ISSUE TITLE
Update repo and README.md with new screenshots

### ISSUE THREAD

**Issue by ole1986** [ole1986/a3-adminhelper#7]
it is necessary to update the images with some fresh screenshots from the ATK once the design is final.
highly appreciate when @Warsheep-GER would take over this task.

Let me know if you think there is something missing for doing screenshot updates.

Thank you in advanced

**Comment by Warsheep-GER** [comment]
i think this isnt a problem for me .

**Comment by ole1986** [comment]
Would you maybe go through the setup written in the README.md - For example the init.sqf located in atk folder must also be added in playerLocal.sqf but its not yet explained in the README.md

THank you in advanced

**Comment by Warsheep-GER** [comment]
ya sure just need to bugfixes my codes first
